name: Java CI with Gradle and Docker

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Docker image
      run: |
        docker build -t saswatcloud/p10-ecommerce-inventory-service:${{ github.run_number }} .
        docker push saswatcloud/p10-ecommerce-inventory-service:${{ github.run_number }}
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    - name: Clean up
      run: docker system prune -af
